Rs 2021 11 23
Tsukihimates/Tsukihime-Translation pull request #131
Opened 2021-12-02 01:49 UTC by rschlaikjer

2021-12-04 14:26 UTC, Avuxo approved these changes
few changes but mostly lgtm

2021-12-04 14:26 UTC, Avuxo commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2.txt
> +I understand that if I truly wish to reduce the number of casualties, I've no choice but to wait here.
this is a British-ism, "I have no choice" sounds a lot more natural

2021-12-04 14:26 UTC, Avuxo commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2.txt
> +"No, that's not what I mean. If we're doing this as a team from now on, instead of out of obligation, then I have a favor to ask of you.
original line is better here imo

2021-12-04 14:26 UTC, Avuxo commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2.txt
> +"...I know that. But this is as much as I can handle. I can't bear to wait any longer." // dropping mentally intentionally here because its awkward in english.
not sure this is an improvement. It changes the register a bit in a way I don't really think fits with these two.

2021-12-04 14:26 UTC, Avuxo commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2B.txt
> +"Chains...? By chains, you mean those chains?"//He says あの鎖 but have we seen any chains to reference? Or is he just saying 'you mean, plain old chains'?
I don't think the chains in question have been referenced or seen up to this point. I think he just means "Do you just mean normal chains" as in "is that all?"

2021-12-04 14:26 UTC, Avuxo commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2B.txt
> +Cutting off a limb? You should give up on such a suicidal act. If you have time to cut off his limbs, you should use that time to sever his life instead. It would be different if he were any other cr
I think this version makes more sense so I'm going to assume it's right. The only source of doubt is that the subject of the past couple of sentences is definitely Shiki.

2021-12-04 14:26 UTC, Avuxo commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2B.txt
> +Even though her eyes were filled with trust, there was a terrible apprehension in her smile.
I can't help but sense a terrible apprehension in her smile.

2021-12-04 14:34 UTC, rschlaikjer commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2.txt
> +"No, that's not what I mean. If we're doing this as a team from now on, instead of out of obligation, then I have a favor to ask of you.
> ここからは義務じゃなくて協力になるんなら、俺の頼みも聞いてほしい。

Hmm, I wanted to capture the ここから / from now on to mark the change in their relationship. I guess I don't feel strongly about it / will revert.

2021-12-04 14:59 UTC, yk1512 requested changes

2021-12-04 14:59 UTC, yk1512 commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3.txt
> +He puts off so much heat that I can't even get close to him.
gives off so much heat

2021-12-04 14:59 UTC, yk1512 commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3.txt
> +"Yeah. During those three days, Vlov will be on the loose. He will go underground and use humans to replenish his blood supply... no, that's not all. From the looks of him, he might even go out and r
あの様子からすると夜の街を徘徊するかもしれない

From the looks of **it**, he might even go out

2021-12-04 14:59 UTC, yk1512 commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2.txt
> +I have to if I really want to defeat that vampire.
> 本当にあの吸血鬼を倒したいのなら

Remove the 'I have to'.

2021-12-04 14:59 UTC, yk1512 commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2.txt
> +"No, that's not what I mean. If we're doing this as a team and not of out of obligation, then I have a favor to ask of you.
there shouldn't be an 'of' before out

2021-12-04 14:59 UTC, yk1512 commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2.txt
> +"So I guess from here on this is a strategy meeting.
comma after on

2021-12-04 14:59 UTC, yk1512 commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2.txt
> +But even so, Arcueid didn't veto my idea.
second Arc could be a she

2021-12-04 14:59 UTC, yk1512 commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2B.txt
> +Meanwhile, I'll hide in advance and attack him from behind during the window where he's fixated on you... or something like that."
when not where

2021-12-04 14:59 UTC, yk1512 commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2B.txt
> +I can only fully restrain him for around ten seconds, so when I do you'll have to burst out from cover and come at him with a swift, head-on attack on his shortest line.
I think removing 'from cover and come at him' would be more concise

2021-12-04 17:07 UTC, rschlaikjer commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2.txt
> +I have to if I really want to defeat that vampire.
As in, just "I really want to defeat that vampire?" I feel like that loses the のなら

2021-12-05 14:44 UTC, yk1512 approved these changes

2021-12-05 14:44 UTC, yk1512 commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2.txt
> +I have to if I really want to defeat that vampire.
I was thinking of 'If I really want to defeat that vampire.' 
If you think that reads weirdly, then I'm ok with keeping the 'I have to.' Just wanted to try to be more faithful to the jp.

2021-12-05 14:50 UTC, rschlaikjer commented on script/1_0_2current_en_script/Arcueid/Day 5/05_00_ARC05_3_2.txt
> +I have to if I really want to defeat that vampire.
Hm, yeah I think that in jp the のなら is a clearer backreference to the previous sentence and it helps to reify it in english by pulling the need to / have to into the line. Hewing closer to the JP I guess you could do a "If I really want to defeat that vampire, that is", but that feels stiff to me.

2021-12-05 14:55 UTC, merged