voices
Tsukihimates/Tsukihime-Translation pull request #1400
Opened 2023-07-15 20:08 UTC by R1kaB3rN

Sometimes, during one's playthrough, voiced interjections (e.g., sigh, ahem, ugh) can be heard and are not captured in the script. Although rare, an interjection appears to typically be in place of '――――' or '……' like in offsets 21916 and 14064. Or other times, not present like in 14180. 
<details>
<summary>21916</summary>

> -- 「――――よかった」
> "%{i}Sigh%{/i}... Thank goodness."

</details>
<details>
<summary>14064</summary>

> -- 「言わずとも分かります。……妙な態度でこちらの気勢を殺がないでください。卑怯です」
> "That much is plain to see. %{i}Sigh%{/i}... Please do not dampen my spirit with your bizarre attitude. It's unfair."

</details>
<details>
<summary>14180</summary>

> -- 「どうやら、兄さんには真面目に返答する気はないみたいですね」
> // Voiced sigh here
> "%{i}Sigh%{/i}... It would appear that you have no intention of answering me seriously."

</details>

In all of these cases, prefer making a comment, italicizing them, and following them with ellipses as the convention just like 14180.

2023-07-19 17:41 UTC, Avuxo requested changes
Adding italics around noises is good, but please avoid adding stuff completely absent from source text.

2023-07-19 17:41 UTC, Avuxo commented on script/Ciel/Day 6/06_01_CIEL06_1_1.txt
> +"That much is plain to see. %{i}Sigh%{/i}...
might be voiced, but absent in source text.

2023-07-19 17:41 UTC, Avuxo commented on script/Ciel/Day 6/06_01_CIEL06_1_2.txt
> +"That much is plain to see. %{i}Sigh%{/i}...
absent in source text.

2023-07-19 17:41 UTC, Avuxo commented on script/Ciel/Day 6/06_01_CIEL06_1_2.txt
> +"It's fine if you don't. %{i}Sigh%{/i}... It's just, I don't seem to have changed either.
absent in source text.

2023-07-20 22:36 UTC, Avuxo commented
> Or is it only acceptable to capture them if there are dashes? For example:

The dashes encode meaning so I'm a little more keen on those. Though, to be honest, I'm not too hot on that sigh either.

2023-07-20 22:38 UTC, Avuxo requested changes

2023-07-20 22:38 UTC, Avuxo commented on script/Arcueid/Day 1/01_00_ARC01_7.txt
> +"I'm ashamed. To be honest, I didn't think it through.
this one encodes extra meaning, replace. We try to avoid lead in "..."s.

2023-07-21 13:24 UTC, Avuxo requested changes

2023-07-21 13:24 UTC, Avuxo commented on script/Arcueid/Day 1/01_00_ARC01_7.txt
> +"I'm ashamed. To be honest, I didn't think it through.
sorry, i worded that weirdly. please revert

2023-07-21 13:24 UTC, Avuxo commented on script/Arcueid/Day 1/01_00_ARC01_7.txt
> +"%{i}Sigh%{/i}.
please revert

2023-07-21 13:24 UTC, Avuxo commented on script/Arcueid/Day 9/09_00_ARC09_4_1.txt
> +"―――Thank goodness..."
A lot of these lines reached their current state after long, arduous, internal discussion that might not necessarily be reflected in comments. As such, I'd appreciate avoiding going for consistency with punctuation like this.

Please revert.

2023-07-25 19:26 UTC, rschlaikjer commented
https://github.com/Tsukihimates/Tsukihime-Translation/pull/1402

2023-07-25 19:26 UTC, closed without merging