Xode PR Arc8_2B
Tsukihimates/Tsukihime-Translation pull request #444
Opened 2022-03-11 11:09 UTC by Xode672

2022-03-11 13:58 UTC, yk1512 requested changes

2022-03-11 13:58 UTC, yk1512 commented on script/Arcueid/Day 8/08_00_ARC08_2B.txt
> + and the only traffic it usually gets is the odd car. //What does it mean by Odd car?
It means that there is not much traffic, only cars pass every so often. Its a standard phrase.

2022-03-11 13:58 UTC, yk1512 commented on script/Arcueid/Day 8/08_00_ARC08_2B.txt
> + careful not to miss any clues as to my attitude.//Is he saying that Ando is taking heavy note on Shiki's attitude or that Ando taking note on everything about Shiki including his attitude?
he's closely monitoring his attitude.

2022-03-11 13:58 UTC, yk1512 commented on script/Arcueid/Day 8/08_00_ARC08_2B.txt
> +What I really want to know about is the guy who'd recently returned to the family, y'know, the eldest son.
revert imo

2022-03-11 13:58 UTC, yk1512 commented on script/Arcueid/Day 8/08_00_ARC08_2B.txt
> + Those sound like fighting words to me, oi".//Are we using "Fighting Words" like the legal term? Tldr: Words with intent to provoke violence/hatred from the target, that cannot be protected/justified
We are not. He's just commenting on the provocative attitude

2022-03-11 14:28 UTC, rschlaikjer commented on script/Arcueid/Day 8/08_00_ARC08_2B.txt
> +...What on earth have I been caught up in here...
Prefer original, it doesn't feel like he's really caught up in anything/ involved yet, just observing

2022-03-11 14:28 UTC, rschlaikjer commented on script/Arcueid/Day 8/08_00_ARC08_2B.txt
> +Maybe I should just call the cops and let them deal with it?
`just` gets a lot of use, including _twice_ on the next line. Maybe leave it off here or find something else, unless it really feels necessary for flow

2022-03-12 20:42 UTC, Avuxo approved these changes

2022-03-12 20:42 UTC, Avuxo commented on script/Arcueid/Day 8/08_00_ARC08_2B.txt
> + I'm curious as to why they're staking out the area in front of our house.
revert

2022-03-13 15:21 UTC, merged